# Project: C106650007_HW_0518
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = C106650007_HW.o
LINKOBJ  = C106650007_HW.o
LIBS     = -L"E:/更/DevCppPortable/MinGW64/lib" -L"E:/更/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/更/DevCppPortable/MinGW64/include" -I"E:/更/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"E:/更/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/更/DevCppPortable/MinGW64/include" -I"E:/更/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"E:/更/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/更/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = C106650007_HW.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

C106650007_HW.o: C106650007_HW.c
	$(CC) -c C106650007_HW.c -o C106650007_HW.o $(CFLAGS)
