# Project: 106650040
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 106650040.o
LINKOBJ  = 106650040.o
LIBS     = -L"D:/DevCppPortable/DevCppPortable/MinGW64/lib" -L"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/DevCppPortable/DevCppPortable/MinGW64/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DevCppPortable/DevCppPortable/MinGW64/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DevCppPortable/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 106650040.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

106650040.o: 106650040.c
	$(CC) -c 106650040.c -o 106650040.o $(CFLAGS)
